name: Publish on NPM
on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]

jobs:
  publish:
    if: contains(join(github.event.commits.*.message, ' | '), '📦 Publicodes v1.0.0-beta.')
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-v2
    - run: yarn install --frozen-lockfile
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_PUBLISH_SECRET }}
        dry-run: ${{ github.ref != 'refs/heads/master' }}
        package: ./core/package.json
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_PUBLISH_SECRET }}
        dry-run: ${{ github.ref != 'refs/heads/master' }}
        package: ./ui-react/package.json
