name: Test
on: [push]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - run: yarn test
  
  test-type:
    name: Type checking
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - run: yarn test:type

  test-example-app:
    name: Test example app
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile
    - working-directory: ./example/publicodes-react
      run: |
        yarn install
        yarn test
